package com.amir.mapper.procurement;

import com.amir.model.procurement.RawMaterialVendor;
import com.amir.model.procurement.RawMaterialVendorExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RawMaterialVendorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    long countByExample(RawMaterialVendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    int deleteByExample(RawMaterialVendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    int insert(RawMaterialVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    int insertSelective(RawMaterialVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    List<RawMaterialVendor> selectByExample(RawMaterialVendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    RawMaterialVendor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RawMaterialVendor record, @Param("example") RawMaterialVendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RawMaterialVendor record, @Param("example") RawMaterialVendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RawMaterialVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RawMaterialVendor record);
}