package com.amir.mapper.pm;

import com.amir.model.pm.PmIn;
import com.amir.model.pm.PmInExample;
import com.amir.vo.PmInVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PmInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    long countByExample(PmInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    int deleteByExample(PmInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    int insert(PmIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    int insertSelective(PmIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    List<PmIn> selectByExample(PmInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    PmIn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PmIn record, @Param("example") PmInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PmIn record, @Param("example") PmInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmIn record);

    List<PmInVo> findList(@Param("pmNo") String pmNo, @Param("name") String name, @Param("type") String type,
                          @Param("startDate") String startDate, @Param("endDate") String endDate);

}