package com.amir.mapper.pm;

import com.amir.model.pm.Pm;
import com.amir.model.pm.PmExample;
import com.amir.model.pm.PmRequstPojo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    long countByExample(PmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    int deleteByExample(PmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    int insert(Pm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    int insertSelective(Pm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    List<Pm> selectByExample(PmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    Pm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Pm record, @Param("example") PmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Pm record, @Param("example") PmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pm record);

    List<Pm> findList(PmRequstPojo pmRequstPojo);

    Integer deleteByID(@Param("integers") List<Integer> integers);

    Integer saveList(@Param("pmList") List<Pm> pmList);

    Pm getByNO(@Param("no") String pmNo);

    Integer deleteByNo(@Param("nos") List<String> nos);
}