package com.amir.mapper.pm;

import com.amir.model.pm.PmOutBill;
import com.amir.model.pm.PmOutBillExample;
import com.amir.vo.PmInAndOutVo;
import com.amir.vo.PmOutBillListVo;
import com.amir.vo.PmOutUpListVo;
import com.amir.vo.PmPlanOutVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PmOutBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    long countByExample(PmOutBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    int deleteByExample(PmOutBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    int insert(PmOutBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    int insertSelective(PmOutBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    List<PmOutBill> selectByExample(PmOutBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    PmOutBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PmOutBill record, @Param("example") PmOutBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PmOutBill record, @Param("example") PmOutBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmOutBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMout_Bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmOutBill record);

    List<PmOutBillListVo> findList(@Param("billNo") String billNo, @Param("orderNo") String orderNo,
                                   @Param("productNo") String productNo);

    PmOutBill getByBillNo(@Param("billNo") String billNo);

    List<PmOutUpListVo> findUpList(@Param("orderNo") String orderNo,
                                   @Param("productNo") String productNo,
                                   @Param("isInput") Integer isInput,
                                   @Param("customerName") Integer customerName);

    Integer count(@Param("orderNo") String orderNo,
                  @Param("productNo") String productNo);

    List<PmInAndOutVo> findInAndOutList(@Param("pmNo") String pmNo,
                                        @Param("pmName") String pmName,
                                        @Param("orderNo") String orderNo,
                                        @Param("operator") String operator,
                                        @Param("startDate") String startDate,
                                        @Param("endDate") String endDate);

    List<PmInAndOutVo> findInList(@Param("pmNo") String pmNo,
                                  @Param("pmName") String pmName,
                                  @Param("orderNo") String orderNo,
                                  @Param("operator") String operator,
                                  @Param("startDate") String startDate,
                                  @Param("endDate") String endDate);

    List<PmInAndOutVo> findOutList(@Param("pmNo") String pmNo,
                                   @Param("pmName") String pmName,
                                   @Param("orderNo") String orderNo,
                                   @Param("operator") String operator,
                                   @Param("startDate") String startDate,
                                   @Param("endDate") String endDate);

    List<PmPlanOutVo> findPlanOutList(@Param("pmNo") String pmNo,
                                      @Param("operator") String operator,
                                      @Param("startDate") String startDate,
                                      @Param("endDate") String endDate);
}