package com.amir.mapper.carton;

import com.amir.model.carton.ShippingMark;
import com.amir.model.carton.ShippingMarkExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShippingMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    long countByExample(ShippingMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    int deleteByExample(ShippingMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    int insert(ShippingMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    int insertSelective(ShippingMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    List<ShippingMark> selectByExample(ShippingMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    ShippingMark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShippingMark record, @Param("example") ShippingMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShippingMark record, @Param("example") ShippingMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShippingMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShippingMark record);
}