package com.amir.mapper.carton;

import com.amir.model.carton.ShippingMarkImage;
import com.amir.model.carton.ShippingMarkImageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShippingMarkImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    long countByExample(ShippingMarkImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    int deleteByExample(ShippingMarkImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    int insert(ShippingMarkImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    int insertSelective(ShippingMarkImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    List<ShippingMarkImage> selectByExample(ShippingMarkImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    ShippingMarkImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShippingMarkImage record, @Param("example") ShippingMarkImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShippingMarkImage record, @Param("example") ShippingMarkImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShippingMarkImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShippingMarkImage record);
}