package com.amir.mapper.order;

import com.amir.model.order.BillNo;
import com.amir.model.order.BillNoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BillNoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    long countByExample(BillNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    int deleteByExample(BillNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    int insert(BillNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    int insertSelective(BillNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    List<BillNo> selectByExample(BillNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    BillNo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BillNo record, @Param("example") BillNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BillNo record, @Param("example") BillNoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BillNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_BillNo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BillNo record);

    BillNo getByTypeAndDate(@Param("type") Integer type, @Param("date") String date);
}