package com.amir.mapper.order;

import com.amir.model.order.MultipleProduction;
import com.amir.model.order.MultipleProductionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MultipleProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    long countByExample(MultipleProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    int deleteByExample(MultipleProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    int insert(MultipleProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    int insertSelective(MultipleProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    List<MultipleProduction> selectByExample(MultipleProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    MultipleProduction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MultipleProduction record, @Param("example") MultipleProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MultipleProduction record, @Param("example") MultipleProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MultipleProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Multiple_Production
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MultipleProduction record);

    List<MultipleProduction> getByProductionNo(@Param("productionNo") String productionNo);
}