package com.amir.mapper.order;

import com.amir.model.order.ProductionProcedure;
import com.amir.model.order.ProductionProcedureExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductionProcedureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    long countByExample(ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    int deleteByExample(ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    int insert(ProductionProcedure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    int insertSelective(ProductionProcedure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    List<ProductionProcedure> selectByExample(ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    ProductionProcedure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductionProcedure record, @Param("example") ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductionProcedure record, @Param("example") ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductionProcedure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Procedure
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductionProcedure record);

    List<ProductionProcedure> findByProductionNo(@Param("productionNo") String productionNo);

    List<ProductionProcedure> getConfigProcedure(@Param("deptName") String deptName, @Param("productionNo") String productionNo);

    Integer deleteByProductionNo(@Param("productionNo") String productionNo);

    Integer procedureCanAssignNum(@Param("orderNo") String orderNo, @Param("productNo") String productNo, @Param("procedureId") Integer procedureId);

    List<ProductionProcedure> isContainZj(@Param("procedureName") String procedureName, @Param("productionNo") String productionNo, @Param("multipleProductionId") Integer multipleProductionId);

    List<ProductionProcedure> getByMultipleId(@Param("multipleId") Integer multipleId);

    List<ProductionProcedure> getByMultipleCantenZJ(@Param("multipleId") Integer multipleId);

    void deletByProductionProcedureId(@Param("id") Integer id);
}