package com.amir.model.carton;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShippingMarkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public ShippingMarkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("clientId is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("clientId is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(Integer value) {
            addCriterion("clientId =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(Integer value) {
            addCriterion("clientId <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(Integer value) {
            addCriterion("clientId >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("clientId >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(Integer value) {
            addCriterion("clientId <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(Integer value) {
            addCriterion("clientId <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<Integer> values) {
            addCriterion("clientId in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<Integer> values) {
            addCriterion("clientId not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(Integer value1, Integer value2) {
            addCriterion("clientId between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("clientId not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNull() {
            addCriterion("productNo is null");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNotNull() {
            addCriterion("productNo is not null");
            return (Criteria) this;
        }

        public Criteria andProductNoEqualTo(String value) {
            addCriterion("productNo =", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotEqualTo(String value) {
            addCriterion("productNo <>", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThan(String value) {
            addCriterion("productNo >", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThanOrEqualTo(String value) {
            addCriterion("productNo >=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThan(String value) {
            addCriterion("productNo <", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThanOrEqualTo(String value) {
            addCriterion("productNo <=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLike(String value) {
            addCriterion("productNo like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotLike(String value) {
            addCriterion("productNo not like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoIn(List<String> values) {
            addCriterion("productNo in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotIn(List<String> values) {
            addCriterion("productNo not in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoBetween(String value1, String value2) {
            addCriterion("productNo between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotBetween(String value1, String value2) {
            addCriterion("productNo not between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdIsNull() {
            addCriterion("outsideMarkId is null");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdIsNotNull() {
            addCriterion("outsideMarkId is not null");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdEqualTo(Integer value) {
            addCriterion("outsideMarkId =", value, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdNotEqualTo(Integer value) {
            addCriterion("outsideMarkId <>", value, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdGreaterThan(Integer value) {
            addCriterion("outsideMarkId >", value, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("outsideMarkId >=", value, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdLessThan(Integer value) {
            addCriterion("outsideMarkId <", value, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdLessThanOrEqualTo(Integer value) {
            addCriterion("outsideMarkId <=", value, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdIn(List<Integer> values) {
            addCriterion("outsideMarkId in", values, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdNotIn(List<Integer> values) {
            addCriterion("outsideMarkId not in", values, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdBetween(Integer value1, Integer value2) {
            addCriterion("outsideMarkId between", value1, value2, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("outsideMarkId not between", value1, value2, "outsideMarkId");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIsNull() {
            addCriterion("outsideMark is null");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIsNotNull() {
            addCriterion("outsideMark is not null");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkEqualTo(String value) {
            addCriterion("outsideMark =", value, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkNotEqualTo(String value) {
            addCriterion("outsideMark <>", value, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkGreaterThan(String value) {
            addCriterion("outsideMark >", value, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkGreaterThanOrEqualTo(String value) {
            addCriterion("outsideMark >=", value, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkLessThan(String value) {
            addCriterion("outsideMark <", value, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkLessThanOrEqualTo(String value) {
            addCriterion("outsideMark <=", value, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkLike(String value) {
            addCriterion("outsideMark like", value, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkNotLike(String value) {
            addCriterion("outsideMark not like", value, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkIn(List<String> values) {
            addCriterion("outsideMark in", values, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkNotIn(List<String> values) {
            addCriterion("outsideMark not in", values, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkBetween(String value1, String value2) {
            addCriterion("outsideMark between", value1, value2, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkNotBetween(String value1, String value2) {
            addCriterion("outsideMark not between", value1, value2, "outsideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdIsNull() {
            addCriterion("insideMarkId is null");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdIsNotNull() {
            addCriterion("insideMarkId is not null");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdEqualTo(Integer value) {
            addCriterion("insideMarkId =", value, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdNotEqualTo(Integer value) {
            addCriterion("insideMarkId <>", value, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdGreaterThan(Integer value) {
            addCriterion("insideMarkId >", value, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("insideMarkId >=", value, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdLessThan(Integer value) {
            addCriterion("insideMarkId <", value, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdLessThanOrEqualTo(Integer value) {
            addCriterion("insideMarkId <=", value, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdIn(List<Integer> values) {
            addCriterion("insideMarkId in", values, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdNotIn(List<Integer> values) {
            addCriterion("insideMarkId not in", values, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdBetween(Integer value1, Integer value2) {
            addCriterion("insideMarkId between", value1, value2, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("insideMarkId not between", value1, value2, "insideMarkId");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIsNull() {
            addCriterion("insideMark is null");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIsNotNull() {
            addCriterion("insideMark is not null");
            return (Criteria) this;
        }

        public Criteria andInsideMarkEqualTo(String value) {
            addCriterion("insideMark =", value, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkNotEqualTo(String value) {
            addCriterion("insideMark <>", value, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkGreaterThan(String value) {
            addCriterion("insideMark >", value, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkGreaterThanOrEqualTo(String value) {
            addCriterion("insideMark >=", value, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkLessThan(String value) {
            addCriterion("insideMark <", value, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkLessThanOrEqualTo(String value) {
            addCriterion("insideMark <=", value, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkLike(String value) {
            addCriterion("insideMark like", value, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkNotLike(String value) {
            addCriterion("insideMark not like", value, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkIn(List<String> values) {
            addCriterion("insideMark in", values, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkNotIn(List<String> values) {
            addCriterion("insideMark not in", values, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkBetween(String value1, String value2) {
            addCriterion("insideMark between", value1, value2, "insideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkNotBetween(String value1, String value2) {
            addCriterion("insideMark not between", value1, value2, "insideMark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andProductNoLikeInsensitive(String value) {
            addCriterion("upper(productNo) like", value.toUpperCase(), "productNo");
            return (Criteria) this;
        }

        public Criteria andOutsideMarkLikeInsensitive(String value) {
            addCriterion("upper(outsideMark) like", value.toUpperCase(), "outsideMark");
            return (Criteria) this;
        }

        public Criteria andInsideMarkLikeInsensitive(String value) {
            addCriterion("upper(insideMark) like", value.toUpperCase(), "insideMark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_shipping_mark
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}