package com.amir.model.carton;

import java.io.Serializable;
import java.util.Date;

public class ShippingMark implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark.id
     *
     * @mbg.generated
     */
    private Integer id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark.clientId
     *
     * @mbg.generated
     */
    private Integer clientId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark.productNo
     *
     * @mbg.generated
     */
    private String productNo;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark.outsideMarkId
     *
     * @mbg.generated
     */
    private Integer outsideMarkId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark.outsideMark
     *
     * @mbg.generated
     */
    private String outsideMark;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark.insideMarkId
     *
     * @mbg.generated
     */
    private Integer insideMarkId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark.insideMark
     *
     * @mbg.generated
     */
    private String insideMark;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark.createTime
     *
     * @mbg.generated
     */
    private Date createTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark.id
     *
     * @return the value of t_shipping_mark.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark.id
     *
     * @param id the value for t_shipping_mark.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark.clientId
     *
     * @return the value of t_shipping_mark.clientId
     *
     * @mbg.generated
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark.clientId
     *
     * @param clientId the value for t_shipping_mark.clientId
     *
     * @mbg.generated
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark.productNo
     *
     * @return the value of t_shipping_mark.productNo
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark.productNo
     *
     * @param productNo the value for t_shipping_mark.productNo
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark.outsideMarkId
     *
     * @return the value of t_shipping_mark.outsideMarkId
     *
     * @mbg.generated
     */
    public Integer getOutsideMarkId() {
        return outsideMarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark.outsideMarkId
     *
     * @param outsideMarkId the value for t_shipping_mark.outsideMarkId
     *
     * @mbg.generated
     */
    public void setOutsideMarkId(Integer outsideMarkId) {
        this.outsideMarkId = outsideMarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark.outsideMark
     *
     * @return the value of t_shipping_mark.outsideMark
     *
     * @mbg.generated
     */
    public String getOutsideMark() {
        return outsideMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark.outsideMark
     *
     * @param outsideMark the value for t_shipping_mark.outsideMark
     *
     * @mbg.generated
     */
    public void setOutsideMark(String outsideMark) {
        this.outsideMark = outsideMark == null ? null : outsideMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark.insideMarkId
     *
     * @return the value of t_shipping_mark.insideMarkId
     *
     * @mbg.generated
     */
    public Integer getInsideMarkId() {
        return insideMarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark.insideMarkId
     *
     * @param insideMarkId the value for t_shipping_mark.insideMarkId
     *
     * @mbg.generated
     */
    public void setInsideMarkId(Integer insideMarkId) {
        this.insideMarkId = insideMarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark.insideMark
     *
     * @return the value of t_shipping_mark.insideMark
     *
     * @mbg.generated
     */
    public String getInsideMark() {
        return insideMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark.insideMark
     *
     * @param insideMark the value for t_shipping_mark.insideMark
     *
     * @mbg.generated
     */
    public void setInsideMark(String insideMark) {
        this.insideMark = insideMark == null ? null : insideMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark.createTime
     *
     * @return the value of t_shipping_mark.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark.createTime
     *
     * @param createTime the value for t_shipping_mark.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark.updateTime
     *
     * @return the value of t_shipping_mark.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark.updateTime
     *
     * @param updateTime the value for t_shipping_mark.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShippingMark other = (ShippingMark) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
                && (this.getProductNo() == null ? other.getProductNo() == null : this.getProductNo().equals(other.getProductNo()))
                && (this.getOutsideMarkId() == null ? other.getOutsideMarkId() == null : this.getOutsideMarkId().equals(other.getOutsideMarkId()))
                && (this.getOutsideMark() == null ? other.getOutsideMark() == null : this.getOutsideMark().equals(other.getOutsideMark()))
                && (this.getInsideMarkId() == null ? other.getInsideMarkId() == null : this.getInsideMarkId().equals(other.getInsideMarkId()))
                && (this.getInsideMark() == null ? other.getInsideMark() == null : this.getInsideMark().equals(other.getInsideMark()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getProductNo() == null) ? 0 : getProductNo().hashCode());
        result = prime * result + ((getOutsideMarkId() == null) ? 0 : getOutsideMarkId().hashCode());
        result = prime * result + ((getOutsideMark() == null) ? 0 : getOutsideMark().hashCode());
        result = prime * result + ((getInsideMarkId() == null) ? 0 : getInsideMarkId().hashCode());
        result = prime * result + ((getInsideMark() == null) ? 0 : getInsideMark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}