package com.amir.model.carton;

import java.io.Serializable;
import java.util.Date;

public class ShippingMarkImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark_image.id
     *
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark_image.fileName
     *
     * @mbg.generated
     */
    private String fileName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark_image.fileType
     *
     * @mbg.generated
     */
    private String fileType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark_image.fileStoreName
     *
     * @mbg.generated
     */
    private String fileStoreName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark_image.createTime
     *
     * @mbg.generated
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shipping_mark_image.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark_image.id
     *
     * @return the value of t_shipping_mark_image.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark_image.id
     *
     * @param id the value for t_shipping_mark_image.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark_image.fileName
     *
     * @return the value of t_shipping_mark_image.fileName
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark_image.fileName
     *
     * @param fileName the value for t_shipping_mark_image.fileName
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark_image.fileType
     *
     * @return the value of t_shipping_mark_image.fileType
     * @mbg.generated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark_image.fileType
     *
     * @param fileType the value for t_shipping_mark_image.fileType
     * @mbg.generated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark_image.fileStoreName
     *
     * @return the value of t_shipping_mark_image.fileStoreName
     * @mbg.generated
     */
    public String getFileStoreName() {
        return fileStoreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark_image.fileStoreName
     *
     * @param fileStoreName the value for t_shipping_mark_image.fileStoreName
     * @mbg.generated
     */
    public void setFileStoreName(String fileStoreName) {
        this.fileStoreName = fileStoreName == null ? null : fileStoreName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark_image.createTime
     *
     * @return the value of t_shipping_mark_image.createTime
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark_image.createTime
     *
     * @param createTime the value for t_shipping_mark_image.createTime
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shipping_mark_image.updateTime
     *
     * @return the value of t_shipping_mark_image.updateTime
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shipping_mark_image.updateTime
     *
     * @param updateTime the value for t_shipping_mark_image.updateTime
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShippingMarkImage other = (ShippingMarkImage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
                && (this.getFileType() == null ? other.getFileType() == null : this.getFileType().equals(other.getFileType()))
                && (this.getFileStoreName() == null ? other.getFileStoreName() == null : this.getFileStoreName().equals(other.getFileStoreName()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping_mark_image
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getFileType() == null) ? 0 : getFileType().hashCode());
        result = prime * result + ((getFileStoreName() == null) ? 0 : getFileStoreName().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}