package com.amir.model.procurement;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RawMaterialVendorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public RawMaterialVendorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFactoryNameIsNull() {
            addCriterion("factoryName is null");
            return (Criteria) this;
        }

        public Criteria andFactoryNameIsNotNull() {
            addCriterion("factoryName is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryNameEqualTo(Integer value) {
            addCriterion("factoryName =", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotEqualTo(Integer value) {
            addCriterion("factoryName <>", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameGreaterThan(Integer value) {
            addCriterion("factoryName >", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameGreaterThanOrEqualTo(Integer value) {
            addCriterion("factoryName >=", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameLessThan(Integer value) {
            addCriterion("factoryName <", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameLessThanOrEqualTo(Integer value) {
            addCriterion("factoryName <=", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameIn(List<Integer> values) {
            addCriterion("factoryName in", values, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotIn(List<Integer> values) {
            addCriterion("factoryName not in", values, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameBetween(Integer value1, Integer value2) {
            addCriterion("factoryName between", value1, value2, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotBetween(Integer value1, Integer value2) {
            addCriterion("factoryName not between", value1, value2, "factoryName");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("productType is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("productType is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(Integer value) {
            addCriterion("productType =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(Integer value) {
            addCriterion("productType <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(Integer value) {
            addCriterion("productType >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("productType >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(Integer value) {
            addCriterion("productType <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(Integer value) {
            addCriterion("productType <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<Integer> values) {
            addCriterion("productType in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<Integer> values) {
            addCriterion("productType not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(Integer value1, Integer value2) {
            addCriterion("productType between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("productType not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andContactPersonIsNull() {
            addCriterion("contactPerson is null");
            return (Criteria) this;
        }

        public Criteria andContactPersonIsNotNull() {
            addCriterion("contactPerson is not null");
            return (Criteria) this;
        }

        public Criteria andContactPersonEqualTo(String value) {
            addCriterion("contactPerson =", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotEqualTo(String value) {
            addCriterion("contactPerson <>", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonGreaterThan(String value) {
            addCriterion("contactPerson >", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonGreaterThanOrEqualTo(String value) {
            addCriterion("contactPerson >=", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLessThan(String value) {
            addCriterion("contactPerson <", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLessThanOrEqualTo(String value) {
            addCriterion("contactPerson <=", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLike(String value) {
            addCriterion("contactPerson like", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotLike(String value) {
            addCriterion("contactPerson not like", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonIn(List<String> values) {
            addCriterion("contactPerson in", values, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotIn(List<String> values) {
            addCriterion("contactPerson not in", values, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonBetween(String value1, String value2) {
            addCriterion("contactPerson between", value1, value2, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotBetween(String value1, String value2) {
            addCriterion("contactPerson not between", value1, value2, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressIsNull() {
            addCriterion("factoryAddress is null");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressIsNotNull() {
            addCriterion("factoryAddress is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressEqualTo(String value) {
            addCriterion("factoryAddress =", value, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressNotEqualTo(String value) {
            addCriterion("factoryAddress <>", value, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressGreaterThan(String value) {
            addCriterion("factoryAddress >", value, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressGreaterThanOrEqualTo(String value) {
            addCriterion("factoryAddress >=", value, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressLessThan(String value) {
            addCriterion("factoryAddress <", value, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressLessThanOrEqualTo(String value) {
            addCriterion("factoryAddress <=", value, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressLike(String value) {
            addCriterion("factoryAddress like", value, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressNotLike(String value) {
            addCriterion("factoryAddress not like", value, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressIn(List<String> values) {
            addCriterion("factoryAddress in", values, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressNotIn(List<String> values) {
            addCriterion("factoryAddress not in", values, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressBetween(String value1, String value2) {
            addCriterion("factoryAddress between", value1, value2, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressNotBetween(String value1, String value2) {
            addCriterion("factoryAddress not between", value1, value2, "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNull() {
            addCriterion("contactPhone is null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNotNull() {
            addCriterion("contactPhone is not null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneEqualTo(String value) {
            addCriterion("contactPhone =", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotEqualTo(String value) {
            addCriterion("contactPhone <>", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThan(String value) {
            addCriterion("contactPhone >", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("contactPhone >=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThan(String value) {
            addCriterion("contactPhone <", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("contactPhone <=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLike(String value) {
            addCriterion("contactPhone like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotLike(String value) {
            addCriterion("contactPhone not like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIn(List<String> values) {
            addCriterion("contactPhone in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotIn(List<String> values) {
            addCriterion("contactPhone not in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneBetween(String value1, String value2) {
            addCriterion("contactPhone between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotBetween(String value1, String value2) {
            addCriterion("contactPhone not between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactFaxIsNull() {
            addCriterion("contactFax is null");
            return (Criteria) this;
        }

        public Criteria andContactFaxIsNotNull() {
            addCriterion("contactFax is not null");
            return (Criteria) this;
        }

        public Criteria andContactFaxEqualTo(String value) {
            addCriterion("contactFax =", value, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxNotEqualTo(String value) {
            addCriterion("contactFax <>", value, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxGreaterThan(String value) {
            addCriterion("contactFax >", value, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxGreaterThanOrEqualTo(String value) {
            addCriterion("contactFax >=", value, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxLessThan(String value) {
            addCriterion("contactFax <", value, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxLessThanOrEqualTo(String value) {
            addCriterion("contactFax <=", value, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxLike(String value) {
            addCriterion("contactFax like", value, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxNotLike(String value) {
            addCriterion("contactFax not like", value, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxIn(List<String> values) {
            addCriterion("contactFax in", values, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxNotIn(List<String> values) {
            addCriterion("contactFax not in", values, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxBetween(String value1, String value2) {
            addCriterion("contactFax between", value1, value2, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactFaxNotBetween(String value1, String value2) {
            addCriterion("contactFax not between", value1, value2, "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactEMailIsNull() {
            addCriterion("contactEMail is null");
            return (Criteria) this;
        }

        public Criteria andContactEMailIsNotNull() {
            addCriterion("contactEMail is not null");
            return (Criteria) this;
        }

        public Criteria andContactEMailEqualTo(String value) {
            addCriterion("contactEMail =", value, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailNotEqualTo(String value) {
            addCriterion("contactEMail <>", value, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailGreaterThan(String value) {
            addCriterion("contactEMail >", value, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailGreaterThanOrEqualTo(String value) {
            addCriterion("contactEMail >=", value, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailLessThan(String value) {
            addCriterion("contactEMail <", value, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailLessThanOrEqualTo(String value) {
            addCriterion("contactEMail <=", value, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailLike(String value) {
            addCriterion("contactEMail like", value, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailNotLike(String value) {
            addCriterion("contactEMail not like", value, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailIn(List<String> values) {
            addCriterion("contactEMail in", values, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailNotIn(List<String> values) {
            addCriterion("contactEMail not in", values, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailBetween(String value1, String value2) {
            addCriterion("contactEMail between", value1, value2, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andContactEMailNotBetween(String value1, String value2) {
            addCriterion("contactEMail not between", value1, value2, "contactEMail");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeIsNull() {
            addCriterion("legalRepresentative is null");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeIsNotNull() {
            addCriterion("legalRepresentative is not null");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeEqualTo(String value) {
            addCriterion("legalRepresentative =", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeNotEqualTo(String value) {
            addCriterion("legalRepresentative <>", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeGreaterThan(String value) {
            addCriterion("legalRepresentative >", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeGreaterThanOrEqualTo(String value) {
            addCriterion("legalRepresentative >=", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeLessThan(String value) {
            addCriterion("legalRepresentative <", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeLessThanOrEqualTo(String value) {
            addCriterion("legalRepresentative <=", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeLike(String value) {
            addCriterion("legalRepresentative like", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeNotLike(String value) {
            addCriterion("legalRepresentative not like", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeIn(List<String> values) {
            addCriterion("legalRepresentative in", values, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeNotIn(List<String> values) {
            addCriterion("legalRepresentative not in", values, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeBetween(String value1, String value2) {
            addCriterion("legalRepresentative between", value1, value2, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeNotBetween(String value1, String value2) {
            addCriterion("legalRepresentative not between", value1, value2, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("bankName is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("bankName is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("bankName =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("bankName <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("bankName >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("bankName >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("bankName <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("bankName <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("bankName like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("bankName not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("bankName in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("bankName not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("bankName between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("bankName not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumIsNull() {
            addCriterion("bankAccountNum is null");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumIsNotNull() {
            addCriterion("bankAccountNum is not null");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumEqualTo(String value) {
            addCriterion("bankAccountNum =", value, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumNotEqualTo(String value) {
            addCriterion("bankAccountNum <>", value, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumGreaterThan(String value) {
            addCriterion("bankAccountNum >", value, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumGreaterThanOrEqualTo(String value) {
            addCriterion("bankAccountNum >=", value, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumLessThan(String value) {
            addCriterion("bankAccountNum <", value, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumLessThanOrEqualTo(String value) {
            addCriterion("bankAccountNum <=", value, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumLike(String value) {
            addCriterion("bankAccountNum like", value, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumNotLike(String value) {
            addCriterion("bankAccountNum not like", value, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumIn(List<String> values) {
            addCriterion("bankAccountNum in", values, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumNotIn(List<String> values) {
            addCriterion("bankAccountNum not in", values, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumBetween(String value1, String value2) {
            addCriterion("bankAccountNum between", value1, value2, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumNotBetween(String value1, String value2) {
            addCriterion("bankAccountNum not between", value1, value2, "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameIsNull() {
            addCriterion("vendorShortName is null");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameIsNotNull() {
            addCriterion("vendorShortName is not null");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameEqualTo(String value) {
            addCriterion("vendorShortName =", value, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameNotEqualTo(String value) {
            addCriterion("vendorShortName <>", value, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameGreaterThan(String value) {
            addCriterion("vendorShortName >", value, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("vendorShortName >=", value, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameLessThan(String value) {
            addCriterion("vendorShortName <", value, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameLessThanOrEqualTo(String value) {
            addCriterion("vendorShortName <=", value, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameLike(String value) {
            addCriterion("vendorShortName like", value, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameNotLike(String value) {
            addCriterion("vendorShortName not like", value, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameIn(List<String> values) {
            addCriterion("vendorShortName in", values, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameNotIn(List<String> values) {
            addCriterion("vendorShortName not in", values, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameBetween(String value1, String value2) {
            addCriterion("vendorShortName between", value1, value2, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameNotBetween(String value1, String value2) {
            addCriterion("vendorShortName not between", value1, value2, "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedIsNull() {
            addCriterion("layerOneCorrugated is null");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedIsNotNull() {
            addCriterion("layerOneCorrugated is not null");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedEqualTo(String value) {
            addCriterion("layerOneCorrugated =", value, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedNotEqualTo(String value) {
            addCriterion("layerOneCorrugated <>", value, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedGreaterThan(String value) {
            addCriterion("layerOneCorrugated >", value, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedGreaterThanOrEqualTo(String value) {
            addCriterion("layerOneCorrugated >=", value, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedLessThan(String value) {
            addCriterion("layerOneCorrugated <", value, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedLessThanOrEqualTo(String value) {
            addCriterion("layerOneCorrugated <=", value, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedLike(String value) {
            addCriterion("layerOneCorrugated like", value, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedNotLike(String value) {
            addCriterion("layerOneCorrugated not like", value, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedIn(List<String> values) {
            addCriterion("layerOneCorrugated in", values, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedNotIn(List<String> values) {
            addCriterion("layerOneCorrugated not in", values, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedBetween(String value1, String value2) {
            addCriterion("layerOneCorrugated between", value1, value2, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedNotBetween(String value1, String value2) {
            addCriterion("layerOneCorrugated not between", value1, value2, "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedIsNull() {
            addCriterion("layerTwoCorrugated is null");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedIsNotNull() {
            addCriterion("layerTwoCorrugated is not null");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedEqualTo(String value) {
            addCriterion("layerTwoCorrugated =", value, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedNotEqualTo(String value) {
            addCriterion("layerTwoCorrugated <>", value, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedGreaterThan(String value) {
            addCriterion("layerTwoCorrugated >", value, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedGreaterThanOrEqualTo(String value) {
            addCriterion("layerTwoCorrugated >=", value, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedLessThan(String value) {
            addCriterion("layerTwoCorrugated <", value, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedLessThanOrEqualTo(String value) {
            addCriterion("layerTwoCorrugated <=", value, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedLike(String value) {
            addCriterion("layerTwoCorrugated like", value, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedNotLike(String value) {
            addCriterion("layerTwoCorrugated not like", value, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedIn(List<String> values) {
            addCriterion("layerTwoCorrugated in", values, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedNotIn(List<String> values) {
            addCriterion("layerTwoCorrugated not in", values, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedBetween(String value1, String value2) {
            addCriterion("layerTwoCorrugated between", value1, value2, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedNotBetween(String value1, String value2) {
            addCriterion("layerTwoCorrugated not between", value1, value2, "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedIsNull() {
            addCriterion("layerThreeCorrugated is null");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedIsNotNull() {
            addCriterion("layerThreeCorrugated is not null");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedEqualTo(String value) {
            addCriterion("layerThreeCorrugated =", value, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedNotEqualTo(String value) {
            addCriterion("layerThreeCorrugated <>", value, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedGreaterThan(String value) {
            addCriterion("layerThreeCorrugated >", value, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedGreaterThanOrEqualTo(String value) {
            addCriterion("layerThreeCorrugated >=", value, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedLessThan(String value) {
            addCriterion("layerThreeCorrugated <", value, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedLessThanOrEqualTo(String value) {
            addCriterion("layerThreeCorrugated <=", value, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedLike(String value) {
            addCriterion("layerThreeCorrugated like", value, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedNotLike(String value) {
            addCriterion("layerThreeCorrugated not like", value, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedIn(List<String> values) {
            addCriterion("layerThreeCorrugated in", values, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedNotIn(List<String> values) {
            addCriterion("layerThreeCorrugated not in", values, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedBetween(String value1, String value2) {
            addCriterion("layerThreeCorrugated between", value1, value2, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedNotBetween(String value1, String value2) {
            addCriterion("layerThreeCorrugated not between", value1, value2, "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexIsNull() {
            addCriterion("shortNameIndex is null");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexIsNotNull() {
            addCriterion("shortNameIndex is not null");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexEqualTo(Integer value) {
            addCriterion("shortNameIndex =", value, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexNotEqualTo(Integer value) {
            addCriterion("shortNameIndex <>", value, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexGreaterThan(Integer value) {
            addCriterion("shortNameIndex >", value, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("shortNameIndex >=", value, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexLessThan(Integer value) {
            addCriterion("shortNameIndex <", value, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexLessThanOrEqualTo(Integer value) {
            addCriterion("shortNameIndex <=", value, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexIn(List<Integer> values) {
            addCriterion("shortNameIndex in", values, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexNotIn(List<Integer> values) {
            addCriterion("shortNameIndex not in", values, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexBetween(Integer value1, Integer value2) {
            addCriterion("shortNameIndex between", value1, value2, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andShortNameIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("shortNameIndex not between", value1, value2, "shortNameIndex");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andContactPersonLikeInsensitive(String value) {
            addCriterion("upper(contactPerson) like", value.toUpperCase(), "contactPerson");
            return (Criteria) this;
        }

        public Criteria andFactoryAddressLikeInsensitive(String value) {
            addCriterion("upper(factoryAddress) like", value.toUpperCase(), "factoryAddress");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLikeInsensitive(String value) {
            addCriterion("upper(contactPhone) like", value.toUpperCase(), "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactFaxLikeInsensitive(String value) {
            addCriterion("upper(contactFax) like", value.toUpperCase(), "contactFax");
            return (Criteria) this;
        }

        public Criteria andContactEMailLikeInsensitive(String value) {
            addCriterion("upper(contactEMail) like", value.toUpperCase(), "contactEMail");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeLikeInsensitive(String value) {
            addCriterion("upper(legalRepresentative) like", value.toUpperCase(), "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andBankNameLikeInsensitive(String value) {
            addCriterion("upper(bankName) like", value.toUpperCase(), "bankName");
            return (Criteria) this;
        }

        public Criteria andBankAccountNumLikeInsensitive(String value) {
            addCriterion("upper(bankAccountNum) like", value.toUpperCase(), "bankAccountNum");
            return (Criteria) this;
        }

        public Criteria andVendorShortNameLikeInsensitive(String value) {
            addCriterion("upper(vendorShortName) like", value.toUpperCase(), "vendorShortName");
            return (Criteria) this;
        }

        public Criteria andLayerOneCorrugatedLikeInsensitive(String value) {
            addCriterion("upper(layerOneCorrugated) like", value.toUpperCase(), "layerOneCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerTwoCorrugatedLikeInsensitive(String value) {
            addCriterion("upper(layerTwoCorrugated) like", value.toUpperCase(), "layerTwoCorrugated");
            return (Criteria) this;
        }

        public Criteria andLayerThreeCorrugatedLikeInsensitive(String value) {
            addCriterion("upper(layerThreeCorrugated) like", value.toUpperCase(), "layerThreeCorrugated");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}