package com.amir.model.procurement;

import java.io.Serializable;
import java.util.Date;

public class RawMaterialVendor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.id
     *
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.factoryName
     *
     * @mbg.generated
     */
    private Integer factoryName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.productType
     *
     * @mbg.generated
     */
    private Integer productType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.contactPerson
     *
     * @mbg.generated
     */
    private String contactPerson;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.factoryAddress
     *
     * @mbg.generated
     */
    private String factoryAddress;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.contactPhone
     *
     * @mbg.generated
     */
    private String contactPhone;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.contactFax
     *
     * @mbg.generated
     */
    private String contactFax;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.contactEMail
     *
     * @mbg.generated
     */
    private String contactEMail;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.legalRepresentative
     *
     * @mbg.generated
     */
    private String legalRepresentative;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.bankName
     *
     * @mbg.generated
     */
    private String bankName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.bankAccountNum
     *
     * @mbg.generated
     */
    private String bankAccountNum;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.vendorShortName
     *
     * @mbg.generated
     */
    private String vendorShortName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.layerOneCorrugated
     *
     * @mbg.generated
     */
    private String layerOneCorrugated;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.layerTwoCorrugated
     *
     * @mbg.generated
     */
    private String layerTwoCorrugated;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.layerThreeCorrugated
     *
     * @mbg.generated
     */
    private String layerThreeCorrugated;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.remark
     *
     * @mbg.generated
     */
    private String remark;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.shortNameIndex
     *
     * @mbg.generated
     */
    private Integer shortNameIndex;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Raw_Material_Vendor.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.id
     *
     * @return the value of t_Raw_Material_Vendor.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.id
     *
     * @param id the value for t_Raw_Material_Vendor.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.factoryName
     *
     * @return the value of t_Raw_Material_Vendor.factoryName
     * @mbg.generated
     */
    public Integer getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.factoryName
     *
     * @param factoryName the value for t_Raw_Material_Vendor.factoryName
     * @mbg.generated
     */
    public void setFactoryName(Integer factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.productType
     *
     * @return the value of t_Raw_Material_Vendor.productType
     * @mbg.generated
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.productType
     *
     * @param productType the value for t_Raw_Material_Vendor.productType
     * @mbg.generated
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.contactPerson
     *
     * @return the value of t_Raw_Material_Vendor.contactPerson
     * @mbg.generated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.contactPerson
     *
     * @param contactPerson the value for t_Raw_Material_Vendor.contactPerson
     * @mbg.generated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.factoryAddress
     *
     * @return the value of t_Raw_Material_Vendor.factoryAddress
     * @mbg.generated
     */
    public String getFactoryAddress() {
        return factoryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.factoryAddress
     *
     * @param factoryAddress the value for t_Raw_Material_Vendor.factoryAddress
     * @mbg.generated
     */
    public void setFactoryAddress(String factoryAddress) {
        this.factoryAddress = factoryAddress == null ? null : factoryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.contactPhone
     *
     * @return the value of t_Raw_Material_Vendor.contactPhone
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.contactPhone
     *
     * @param contactPhone the value for t_Raw_Material_Vendor.contactPhone
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.contactFax
     *
     * @return the value of t_Raw_Material_Vendor.contactFax
     * @mbg.generated
     */
    public String getContactFax() {
        return contactFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.contactFax
     *
     * @param contactFax the value for t_Raw_Material_Vendor.contactFax
     * @mbg.generated
     */
    public void setContactFax(String contactFax) {
        this.contactFax = contactFax == null ? null : contactFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.contactEMail
     *
     * @return the value of t_Raw_Material_Vendor.contactEMail
     * @mbg.generated
     */
    public String getContactEMail() {
        return contactEMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.contactEMail
     *
     * @param contactEMail the value for t_Raw_Material_Vendor.contactEMail
     * @mbg.generated
     */
    public void setContactEMail(String contactEMail) {
        this.contactEMail = contactEMail == null ? null : contactEMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.legalRepresentative
     *
     * @return the value of t_Raw_Material_Vendor.legalRepresentative
     * @mbg.generated
     */
    public String getLegalRepresentative() {
        return legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.legalRepresentative
     *
     * @param legalRepresentative the value for t_Raw_Material_Vendor.legalRepresentative
     * @mbg.generated
     */
    public void setLegalRepresentative(String legalRepresentative) {
        this.legalRepresentative = legalRepresentative == null ? null : legalRepresentative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.bankName
     *
     * @return the value of t_Raw_Material_Vendor.bankName
     * @mbg.generated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.bankName
     *
     * @param bankName the value for t_Raw_Material_Vendor.bankName
     * @mbg.generated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.bankAccountNum
     *
     * @return the value of t_Raw_Material_Vendor.bankAccountNum
     * @mbg.generated
     */
    public String getBankAccountNum() {
        return bankAccountNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.bankAccountNum
     *
     * @param bankAccountNum the value for t_Raw_Material_Vendor.bankAccountNum
     * @mbg.generated
     */
    public void setBankAccountNum(String bankAccountNum) {
        this.bankAccountNum = bankAccountNum == null ? null : bankAccountNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.vendorShortName
     *
     * @return the value of t_Raw_Material_Vendor.vendorShortName
     * @mbg.generated
     */
    public String getVendorShortName() {
        return vendorShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.vendorShortName
     *
     * @param vendorShortName the value for t_Raw_Material_Vendor.vendorShortName
     * @mbg.generated
     */
    public void setVendorShortName(String vendorShortName) {
        this.vendorShortName = vendorShortName == null ? null : vendorShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.layerOneCorrugated
     *
     * @return the value of t_Raw_Material_Vendor.layerOneCorrugated
     * @mbg.generated
     */
    public String getLayerOneCorrugated() {
        return layerOneCorrugated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.layerOneCorrugated
     *
     * @param layerOneCorrugated the value for t_Raw_Material_Vendor.layerOneCorrugated
     * @mbg.generated
     */
    public void setLayerOneCorrugated(String layerOneCorrugated) {
        this.layerOneCorrugated = layerOneCorrugated == null ? null : layerOneCorrugated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.layerTwoCorrugated
     *
     * @return the value of t_Raw_Material_Vendor.layerTwoCorrugated
     * @mbg.generated
     */
    public String getLayerTwoCorrugated() {
        return layerTwoCorrugated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.layerTwoCorrugated
     *
     * @param layerTwoCorrugated the value for t_Raw_Material_Vendor.layerTwoCorrugated
     * @mbg.generated
     */
    public void setLayerTwoCorrugated(String layerTwoCorrugated) {
        this.layerTwoCorrugated = layerTwoCorrugated == null ? null : layerTwoCorrugated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.layerThreeCorrugated
     *
     * @return the value of t_Raw_Material_Vendor.layerThreeCorrugated
     * @mbg.generated
     */
    public String getLayerThreeCorrugated() {
        return layerThreeCorrugated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.layerThreeCorrugated
     *
     * @param layerThreeCorrugated the value for t_Raw_Material_Vendor.layerThreeCorrugated
     * @mbg.generated
     */
    public void setLayerThreeCorrugated(String layerThreeCorrugated) {
        this.layerThreeCorrugated = layerThreeCorrugated == null ? null : layerThreeCorrugated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.remark
     *
     * @return the value of t_Raw_Material_Vendor.remark
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.remark
     *
     * @param remark the value for t_Raw_Material_Vendor.remark
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.shortNameIndex
     *
     * @return the value of t_Raw_Material_Vendor.shortNameIndex
     * @mbg.generated
     */
    public Integer getShortNameIndex() {
        return shortNameIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.shortNameIndex
     *
     * @param shortNameIndex the value for t_Raw_Material_Vendor.shortNameIndex
     * @mbg.generated
     */
    public void setShortNameIndex(Integer shortNameIndex) {
        this.shortNameIndex = shortNameIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.updateTime
     *
     * @return the value of t_Raw_Material_Vendor.updateTime
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.updateTime
     *
     * @param updateTime the value for t_Raw_Material_Vendor.updateTime
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Raw_Material_Vendor.createTime
     *
     * @return the value of t_Raw_Material_Vendor.createTime
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Raw_Material_Vendor.createTime
     *
     * @param createTime the value for t_Raw_Material_Vendor.createTime
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RawMaterialVendor other = (RawMaterialVendor) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getFactoryName() == null ? other.getFactoryName() == null : this.getFactoryName().equals(other.getFactoryName()))
                && (this.getProductType() == null ? other.getProductType() == null : this.getProductType().equals(other.getProductType()))
                && (this.getContactPerson() == null ? other.getContactPerson() == null : this.getContactPerson().equals(other.getContactPerson()))
                && (this.getFactoryAddress() == null ? other.getFactoryAddress() == null : this.getFactoryAddress().equals(other.getFactoryAddress()))
                && (this.getContactPhone() == null ? other.getContactPhone() == null : this.getContactPhone().equals(other.getContactPhone()))
                && (this.getContactFax() == null ? other.getContactFax() == null : this.getContactFax().equals(other.getContactFax()))
                && (this.getContactEMail() == null ? other.getContactEMail() == null : this.getContactEMail().equals(other.getContactEMail()))
                && (this.getLegalRepresentative() == null ? other.getLegalRepresentative() == null : this.getLegalRepresentative().equals(other.getLegalRepresentative()))
                && (this.getBankName() == null ? other.getBankName() == null : this.getBankName().equals(other.getBankName()))
                && (this.getBankAccountNum() == null ? other.getBankAccountNum() == null : this.getBankAccountNum().equals(other.getBankAccountNum()))
                && (this.getVendorShortName() == null ? other.getVendorShortName() == null : this.getVendorShortName().equals(other.getVendorShortName()))
                && (this.getLayerOneCorrugated() == null ? other.getLayerOneCorrugated() == null : this.getLayerOneCorrugated().equals(other.getLayerOneCorrugated()))
                && (this.getLayerTwoCorrugated() == null ? other.getLayerTwoCorrugated() == null : this.getLayerTwoCorrugated().equals(other.getLayerTwoCorrugated()))
                && (this.getLayerThreeCorrugated() == null ? other.getLayerThreeCorrugated() == null : this.getLayerThreeCorrugated().equals(other.getLayerThreeCorrugated()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
                && (this.getShortNameIndex() == null ? other.getShortNameIndex() == null : this.getShortNameIndex().equals(other.getShortNameIndex()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Raw_Material_Vendor
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFactoryName() == null) ? 0 : getFactoryName().hashCode());
        result = prime * result + ((getProductType() == null) ? 0 : getProductType().hashCode());
        result = prime * result + ((getContactPerson() == null) ? 0 : getContactPerson().hashCode());
        result = prime * result + ((getFactoryAddress() == null) ? 0 : getFactoryAddress().hashCode());
        result = prime * result + ((getContactPhone() == null) ? 0 : getContactPhone().hashCode());
        result = prime * result + ((getContactFax() == null) ? 0 : getContactFax().hashCode());
        result = prime * result + ((getContactEMail() == null) ? 0 : getContactEMail().hashCode());
        result = prime * result + ((getLegalRepresentative() == null) ? 0 : getLegalRepresentative().hashCode());
        result = prime * result + ((getBankName() == null) ? 0 : getBankName().hashCode());
        result = prime * result + ((getBankAccountNum() == null) ? 0 : getBankAccountNum().hashCode());
        result = prime * result + ((getVendorShortName() == null) ? 0 : getVendorShortName().hashCode());
        result = prime * result + ((getLayerOneCorrugated() == null) ? 0 : getLayerOneCorrugated().hashCode());
        result = prime * result + ((getLayerTwoCorrugated() == null) ? 0 : getLayerTwoCorrugated().hashCode());
        result = prime * result + ((getLayerThreeCorrugated() == null) ? 0 : getLayerThreeCorrugated().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getShortNameIndex() == null) ? 0 : getShortNameIndex().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}