package com.amir.mapper.sys;

import com.amir.model.sys.ShortUrlMapping;
import com.amir.model.sys.ShortUrlMappingExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShortUrlMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    long countByExample(ShortUrlMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    int deleteByExample(ShortUrlMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    int insert(ShortUrlMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    int insertSelective(ShortUrlMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    List<ShortUrlMapping> selectByExample(ShortUrlMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    ShortUrlMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShortUrlMapping record, @Param("example") ShortUrlMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShortUrlMapping record, @Param("example") ShortUrlMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShortUrlMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ShortUrlMapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShortUrlMapping record);

    String getByShort(@Param("shortUrl") String shortUrl);
}