package com.amir.mapper.sys;

import com.amir.model.sys.Sysmenu;
import com.amir.model.sys.SysmenuExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysmenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    long countByExample(SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    int deleteByExample(SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    int insert(Sysmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    int insertSelective(Sysmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    List<Sysmenu> selectByExample(SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    Sysmenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Sysmenu record, @Param("example") SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Sysmenu record, @Param("example") SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sysmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sysmenu record);
}